### ISSUE TITLE
Enhancement: Upgrade React Router to its Latest Version

### ISSUE THREAD

**Issue by rwieruch** [wrobin/favesound-redux#32]
React Router has a lot of breaking changes when using the latest version. Maybe it would be a great PR to upgrade react-router (perhaps also react-redux-router or even get rid of it) to its latest version.

**Comment by chriszhangusc** [comment]
Working on it.

**Comment by chriszhangusc** [comment]
I have finished the router upgrade, however, I want to propose some changes:

1. Change browse URL from http://localhost:8080/browse?genre=Minimal to http://localhost:8080/browse/Minimal because in react router v4 we need to parse the query string, the second way it will make the code easier and cleaner to parse the genre from URL.
[See:](https://github.com/ReactTraining/react-router/issues/4410)

2. Simplify the App Logo to point to browse the default genre, right now it is pointing to the currently selected route. 

3. Probably a typo: change filename from constants/authentification to constants/authentication.

**Comment by rwieruch** [comment]
Everything sounds great! I would say, go for it 👍

**Comment by rwieruch** [comment]
https://github.com/rwieruch/favesound-redux/pull/40 perfectly done by @MiniPekka
