### ISSUE TITLE
Failed to play song

### ISSUE THREAD

**Issue by chriszhangusc** [wrobin/favesound-redux#37]
<img width="874" alt="screen shot 2017-06-06 at 5 39 01 am" src="https://cloud.githubusercontent.com/assets/15867071/26830313/4ebe368e-4a7d-11e7-97c5-da6b0fb7b5c3.png">

This happens when I try to play a song. I think this may be related to too many requests have been made under one client_id, should we use an alternative client_id?

**Comment by rwieruch** [comment]
Yes, I think since the client_id is public, people might use it for their own projects... Maybe I would see the currently used client_id as deprecated and advice people in the README.md installation guide to use their own and how to apply at SoundCloud for it? Would you know another solution to the problem @MiniPekka ? Thanks for bringing this up.

**Comment by chriszhangusc** [comment]
@rwieruch I would say just try to switch to another clientId and see how it goes. 

I think it would also be better to use client_id instead of oauth_token to make the audio src requests because oauth_token is valuable since it will take up to a month for SoundCloud to give you one which sucks by the way. client_id, on the other hand, does not have this problem. We can have a pool of client_ids and whenever we need to make a request for a soundtrack, we can randomly fetch one from the pool and attach it to the request.

**Comment by rwieruch** [comment]
@MiniPekka I never used the new registration process by SoundCloud. Wouldn't you have to wait for the client_id as well for one month? I had this problem in my [React Redux SC tutorial ](https://www.robinwieruch.de/the-soundcloud-client-in-react-redux/) when SoundCloud changed their registration process and readers of the tutorial had to wait for their key. I am curious because you speak about the client_id. Is there a workaround to the registration process? Regardless of that your idea sounds great if it would be possible.

**Comment by chriszhangusc** [comment]
@rwieruch Sorry my bad, you are right, you'll also have to wait to get the client_id. I've mistaken it for something else here. However, I got a bunch of client_ids, maybe I can do a temporary fix with one of my client_ids to make it work again.

**Comment by rwieruch** [comment]
@MiniPekka that sounds great. Either way, I think I have to try again to write up someone from SoundCloud about thei registration process...

**Comment by rwieruch** [comment]
Fixed in https://github.com/rwieruch/favesound-redux/pull/43 by @MiniPekka

**Comment by rwieruch** [comment]
@MiniPekka are you active on Twitter? Would like to reach you there :)

**Comment by chriszhangusc** [comment]
@rwieruch Yeah, I lost my old one and just started a new one today, I'll be active there. 
@AngryChris_Z
