### ISSUE TITLE
[Refactor] Use callback refs instead of string refs

### ISSUE THREAD

**Issue by chriszhangusc** [wrobin/favesound-redux#66]
I think we should refactor string refs to callback refs since the former has some issues as per react documentation: https://facebook.github.io/react/docs/refs-and-the-dom.html

**Comment by rwieruch** [comment]
Oh. Didn't see that @MiniPekka Where are the refs used? Maybe it would be great to update it properly, because the project is used by React newcomers to see recent practices.

see https://www.robinwieruch.de/react-ref-attribute-dom-node/

**Comment by Duske** [comment]
I would like to tackle this issue if that's okay :)

**Comment by rwieruch** [comment]
I think @MiniPekka didn't start yet, so go for it :) Thank you for your help!

**Comment by Duske** [comment]
There seems to be an issue which I'm still trying to wrap my head around:

The only component that needs to be adjusted is the Player component, where [ref is used to control the <audio> element](https://github.com/rwieruch/favesound-redux/blob/master/src/components/Player/index.js#L223).
Unfortunately, a simple rewrite with a ref callback function does not do the trick, the audio component ref does not get passed, which is why a song cannot be played.
I put these very small changes in [this branch](https://github.com/Duske/favesound-redux/commit/4e43a0e9448812d7053037d09434e6dc58728ba0).

I've also tried to bind it within the constructor like `this.setAudioPosition()` for example, but with no success. Maybe the problem is using the right `this` since the `render() ` method calls another function `renderNav()` inside it, which renders the audio element.

**Comment by gokulchandra** [comment]
@Duske I think you missed out refactoring the references. 
@rwieruch Please take look at PR #73 .

**Comment by Duske** [comment]
Damn, I could swear I tried this as well :D Thanks for pointing out my mistake, looks good to me :)

**Comment by rwieruch** [comment]
Thanks so much to both of you for contributing to this repository 🎉
